// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: examples/book/book.proto

package book

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BookService_GetBook_FullMethodName           = "/book.BookService/GetBook"
	BookService_GetBooksViaAuthor_FullMethodName = "/book.BookService/GetBooksViaAuthor"
	BookService_GetGreatestBook_FullMethodName   = "/book.BookService/GetGreatestBook"
	BookService_GetBooks_FullMethodName          = "/book.BookService/GetBooks"
)

// BookServiceClient is the client API for BookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookServiceClient interface {
	GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*Book, error)
	GetBooksViaAuthor(ctx context.Context, in *GetBookViaAuthor, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Book], error)
	GetGreatestBook(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[GetBookRequest, Book], error)
	GetBooks(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GetBookRequest, Book], error)
}

type bookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookServiceClient(cc grpc.ClientConnInterface) BookServiceClient {
	return &bookServiceClient{cc}
}

func (c *bookServiceClient) GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*Book, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Book)
	err := c.cc.Invoke(ctx, BookService_GetBook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) GetBooksViaAuthor(ctx context.Context, in *GetBookViaAuthor, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Book], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BookService_ServiceDesc.Streams[0], BookService_GetBooksViaAuthor_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetBookViaAuthor, Book]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BookService_GetBooksViaAuthorClient = grpc.ServerStreamingClient[Book]

func (c *bookServiceClient) GetGreatestBook(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[GetBookRequest, Book], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BookService_ServiceDesc.Streams[1], BookService_GetGreatestBook_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetBookRequest, Book]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BookService_GetGreatestBookClient = grpc.ClientStreamingClient[GetBookRequest, Book]

func (c *bookServiceClient) GetBooks(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GetBookRequest, Book], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BookService_ServiceDesc.Streams[2], BookService_GetBooks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetBookRequest, Book]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BookService_GetBooksClient = grpc.BidiStreamingClient[GetBookRequest, Book]

// BookServiceServer is the server API for BookService service.
// All implementations must embed UnimplementedBookServiceServer
// for forward compatibility.
type BookServiceServer interface {
	GetBook(context.Context, *GetBookRequest) (*Book, error)
	GetBooksViaAuthor(*GetBookViaAuthor, grpc.ServerStreamingServer[Book]) error
	GetGreatestBook(grpc.ClientStreamingServer[GetBookRequest, Book]) error
	GetBooks(grpc.BidiStreamingServer[GetBookRequest, Book]) error
	mustEmbedUnimplementedBookServiceServer()
}

// UnimplementedBookServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBookServiceServer struct{}

func (UnimplementedBookServiceServer) GetBook(context.Context, *GetBookRequest) (*Book, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBook not implemented")
}
func (UnimplementedBookServiceServer) GetBooksViaAuthor(*GetBookViaAuthor, grpc.ServerStreamingServer[Book]) error {
	return status.Errorf(codes.Unimplemented, "method GetBooksViaAuthor not implemented")
}
func (UnimplementedBookServiceServer) GetGreatestBook(grpc.ClientStreamingServer[GetBookRequest, Book]) error {
	return status.Errorf(codes.Unimplemented, "method GetGreatestBook not implemented")
}
func (UnimplementedBookServiceServer) GetBooks(grpc.BidiStreamingServer[GetBookRequest, Book]) error {
	return status.Errorf(codes.Unimplemented, "method GetBooks not implemented")
}
func (UnimplementedBookServiceServer) mustEmbedUnimplementedBookServiceServer() {}
func (UnimplementedBookServiceServer) testEmbeddedByValue()                     {}

// UnsafeBookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookServiceServer will
// result in compilation errors.
type UnsafeBookServiceServer interface {
	mustEmbedUnimplementedBookServiceServer()
}

func RegisterBookServiceServer(s grpc.ServiceRegistrar, srv BookServiceServer) {
	// If the following call pancis, it indicates UnimplementedBookServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BookService_ServiceDesc, srv)
}

func _BookService_GetBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).GetBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookService_GetBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).GetBook(ctx, req.(*GetBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_GetBooksViaAuthor_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetBookViaAuthor)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BookServiceServer).GetBooksViaAuthor(m, &grpc.GenericServerStream[GetBookViaAuthor, Book]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BookService_GetBooksViaAuthorServer = grpc.ServerStreamingServer[Book]

func _BookService_GetGreatestBook_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BookServiceServer).GetGreatestBook(&grpc.GenericServerStream[GetBookRequest, Book]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BookService_GetGreatestBookServer = grpc.ClientStreamingServer[GetBookRequest, Book]

func _BookService_GetBooks_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BookServiceServer).GetBooks(&grpc.GenericServerStream[GetBookRequest, Book]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BookService_GetBooksServer = grpc.BidiStreamingServer[GetBookRequest, Book]

// BookService_ServiceDesc is the grpc.ServiceDesc for BookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "book.BookService",
	HandlerType: (*BookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBook",
			Handler:    _BookService_GetBook_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetBooksViaAuthor",
			Handler:       _BookService_GetBooksViaAuthor_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetGreatestBook",
			Handler:       _BookService_GetGreatestBook_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetBooks",
			Handler:       _BookService_GetBooks_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "examples/book/book.proto",
}
